version: '3.8'

services:
  incident-app:
    image: incident-app:latest
    container_name: MongoClusterAtlas
    env_file:
      - ./backend/.env
    ports:
      - "3333:3333"
    environment:
      MONGO_URI: mongodb+srv://${DB_USER}:${DB_PASSWORD}@${DB_CLUSTER}.mongodb.net/${DB_NAME}?retryWrites=true&w=majority
